package startup

import (
	"github.com/ZMS-DevOps/search-service/domain"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

var accommodations = []*domain.Accommodation{
	{
		Id:           getObjectId("6643a56c9dea1760db469b7b"),
		Name:         "Wailea Beach Resort",
		Location:     "Hawaii",
		MainPhoto:    "photo1.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 2, Max: 6},
		DefaultPrice: domain.DefaultPrice{Price: 500.00, Type: domain.PerApartmentUnit},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("6643bdc7240f80f13b5d18d7"),
		Name:         "Cozy Cottage",
		Location:     "Bali",
		MainPhoto:    "photo4.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 1, Max: 4},
		DefaultPrice: domain.DefaultPrice{Price: 75.00, Type: domain.PerGuest},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("ff43bdc7240f80f13b5d23e8"),
		Name:         "Luxury Villa",
		Location:     "Bali",
		MainPhoto:    "photo31.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 2, Max: 8},
		DefaultPrice: domain.DefaultPrice{Price: 1000.00, Type: domain.PerApartmentUnit},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("1143bdc7240f80f13b5d24e9"),
		Name:         "Balinese Bungalow",
		Location:     "Bali",
		MainPhoto:    "photo34.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 1, Max: 4},
		DefaultPrice: domain.DefaultPrice{Price: 200.00, Type: domain.PerGuest},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("2243bdc7240f80f13b5d25e0"),
		Name:         "Cliffside Retreat",
		Location:     "Bali",
		MainPhoto:    "photo37.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 2, Max: 6},
		DefaultPrice: domain.DefaultPrice{Price: 800.00, Type: domain.PerApartmentUnit},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("3343bdc7240f80f13b5d26e1"),
		Name:         "Ubud Villa",
		Location:     "Bali",
		MainPhoto:    "photo40.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 2, Max: 5},
		DefaultPrice: domain.DefaultPrice{Price: 650.00, Type: domain.PerApartmentUnit},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("7743a6dc9dea1760db469b8c"),
		Name:         "Mountain Retreat",
		Location:     "Switzerland",
		MainPhoto:    "photo7.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 4, Max: 10},
		DefaultPrice: domain.DefaultPrice{Price: 1000.00, Type: domain.PerApartmentUnit},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("8843bdc7240f80f13b5d19e7"),
		Name:         "Urban Loft",
		Location:     "New York",
		MainPhoto:    "photo10.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 1, Max: 3},
		DefaultPrice: domain.DefaultPrice{Price: 200.00, Type: domain.PerGuest},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("4443bdc7240f80f13b5d27e2"),
		Name:         "Central Park Apartment",
		Location:     "New York",
		MainPhoto:    "photo43.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 2, Max: 5},
		DefaultPrice: domain.DefaultPrice{Price: 350.00, Type: domain.PerApartmentUnit},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("5543bdc7240f80f13b5d28e3"),
		Name:         "Brooklyn Brownstone",
		Location:     "New York",
		MainPhoto:    "photo46.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 1, Max: 6},
		DefaultPrice: domain.DefaultPrice{Price: 300.00, Type: domain.PerGuest},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("6643bdc7240f80f13b5d29e4"),
		Name:         "Times Square Studio",
		Location:     "New York",
		MainPhoto:    "photo49.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 1, Max: 2},
		DefaultPrice: domain.DefaultPrice{Price: 250.00, Type: domain.PerGuest},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("9943a7dc9dea1760db469b9d"),
		Name:         "Beachfront Villa",
		Location:     "Maldives",
		MainPhoto:    "photo13.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 2, Max: 8},
		DefaultPrice: domain.DefaultPrice{Price: 1500.00, Type: domain.PerApartmentUnit},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("aa43bdc7240f80f13b5d20d7"),
		Name:         "Country Farmhouse",
		Location:     "France",
		MainPhoto:    "photo16.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 2, Max: 5},
		DefaultPrice: domain.DefaultPrice{Price: 300.00, Type: domain.PerGuest},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("bb43a8dc9dea1760db469c1e"),
		Name:         "Desert Oasis",
		Location:     "Dubai",
		MainPhoto:    "photo19.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 2, Max: 4},
		DefaultPrice: domain.DefaultPrice{Price: 750.00, Type: domain.PerGuest},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("cc43bdc7240f80f13b5d21e7"),
		Name:         "Tropical Paradise",
		Location:     "Thailand",
		MainPhoto:    "photo22.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 1, Max: 6},
		DefaultPrice: domain.DefaultPrice{Price: 600.00, Type: domain.PerApartmentUnit},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("dd43a9dc9dea1760db469c2f"),
		Name:         "Safari Lodge",
		Location:     "Kenya",
		MainPhoto:    "photo25.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 2, Max: 12},
		DefaultPrice: domain.DefaultPrice{Price: 1200.00, Type: domain.PerApartmentUnit},
		SpecialPrice: []domain.SpecialPrice{},
	},
	{
		Id:           getObjectId("ee43bdc7240f80f13b5d22e7"),
		Name:         "Lake House",
		Location:     "Canada",
		MainPhoto:    "photo28.jpg",
		Rating:       0,
		GuestNumber:  domain.GuestNumber{Min: 1, Max: 6},
		DefaultPrice: domain.DefaultPrice{Price: 400.00, Type: domain.PerApartmentUnit},
		SpecialPrice: []domain.SpecialPrice{},
	},
}

func getObjectId(id string) primitive.ObjectID {
	if objectId, err := primitive.ObjectIDFromHex(id); err == nil {
		return objectId
	}
	return primitive.NewObjectID()
}
