apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: search
          image: devopszms2024/zms-devops-search-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          envFrom:
            - secretRef:
                name: mongodb-search-secret
            - configMapRef:
                name: search-configmap
            - configMapRef:
                name: mongodb-search-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: search
#  namespace: backend
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      name: http
      port: 8085
      targetPort: 8085
    - protocol: TCP
      name: grpc
      port: 8002
      targetPort: 8002