apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  namespace: backend
  name: search
spec:	
  selector:
    matchLabels:
       app: search
  rules:
    - to:
        - operation:
            methods: [ "GET", "POST" ]
            paths: [ "/search/health", "/search/all"]
    - to:
        - operation:
            methods: [ "GET", "POST", "PUT", "DELETE" ]
            paths: [ "/search.SearchService/*" ]
    - to:
        - operation:
            methods: [ "GET" ]
            paths: [ "/search/*" ]
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "host", "guest" ]