apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: backend
  name: search
spec:
  hosts:
    - "*"
  gateways:
    - api-gateway
  http:
    - match:
        - uri:
            prefix: "/search"
      route:
        - destination:
            host: search.backend.svc.cluster.local
            port:
              number: 8085
